name: wanderlust-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.40.0
    - google-generativeai==0.8.3
    - groq==0.11.0
    - folium==0.17.0
    - streamlit-folium==0.23.0
    - geopy==2.4.1
    - requests==2.32.3
    - python-dotenv==1.0.1